In [3]:
!pip install qrcode[pil]
import qrcode
import random
import string
import pandas as pd
from PIL import Image

# دالة لتوليد رقم تسلسلي حقيقي
def generate_real_serial_number():
    # توليد رقم تسلسلي حقيقي (مثال: 10 أرقام حقيقية)
    serial_number = ''.join(random.choices(string.digits, k=10))  # 10 أرقام حقيقية
    return serial_number

# دالة لتوليد رقم تسلسلي مزيف
def generate_fake_serial_number():
    # توليد رقم تسلسلي مزيف (مثال: 10 أرقام عشوائية)
    serial_number = ''.join(random.choices(string.digits, k=10))  # 10 أرقام مزيفة
    return serial_number

# دالة لتوليد QR code من رقم تسلسلي
def generate_qr_code(serial_number, is_real):
    qr = qrcode.QRCode(version=1, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=4)
    qr.add_data(serial_number)
    qr.make(fit=True)

    img = qr.make_image(fill='black', back_color='white')
    img_path = f'qr_code_{serial_number}.png'
    img.save(img_path)
    return img_path

# توليد 1000 رقم تسلسلي حقيقي
def generate_real_data():
    real_data = []
    for _ in range(1000):  # توليد 1000 رقم حقيقي
        real_serial = generate_real_serial_number()
        real_qr_path = generate_qr_code(real_serial, True)
        real_data.append({"serial_number": real_serial, "qr_code_path": real_qr_path, "is_real": True})
    return real_data

# توليد 1000 رقم تسلسلي مزيف
def generate_fake_data():
    fake_data = []
    for _ in range(1000):  # توليد 1000 رقم مزيف
        fake_serial = generate_fake_serial_number()
        fake_qr_path = generate_qr_code(fake_serial, False)
        fake_data.append({"serial_number": fake_serial, "qr_code_path": fake_qr_path, "is_real": False})
    return fake_data

# فصل توليد الأرقام الحقيقية والمزيفة
real_data = generate_real_data()
fake_data = generate_fake_data()

# دمج البيانات الحقيقية والمزيفة في قاعدة بيانات واحدة
all_data = real_data + fake_data

# تحويل البيانات إلى DataFrame
df = pd.DataFrame(all_data)

# حفظ قاعدة البيانات في ملف CSV
df.to_csv('serial_numbers_with_qr_codes_separated.csv', index=False)

# عرض بعض البيانات للتأكد
print(df.head())


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 3.5 MB/s eta 0:00:00
  serial_number            qr_code_path  is_real
0    3318969548  qr_code_3318969548.png     True
1    6798490167  qr_code_6798490167.png     True
2    8659305112  qr_code_8659305112.png     True
3    3876647307  qr_code_3876647307.png     True
4    4492775533  qr_code_4492775533.png     True


In [4]:
import pandas as pd

# قراءة البيانات من ملف CSV
df = pd.read_csv('serial_numbers_with_qr_codes_separated.csv')

# عرض أول 10 صفوف من البيانات
print("عرض أول 10 صفوف من البيانات:")
print(df.head(10))

# عرض عدد الأرقام الحقيقية والمزيفة
real_count = df[df['is_real'] == True].shape[0]
fake_count = df[df['is_real'] == False].shape[0]

print(f"\nعدد الأرقام الحقيقية: {real_count}")
print(f"عدد الأرقام المزيفة: {fake_count}")

# عرض البيانات الحقيقية فقط
print("\nعرض البيانات الحقيقية:")
print(df[df['is_real'] == True])

# عرض البيانات المزيفة فقط
print("\nعرض البيانات المزيفة:")
print(df[df['is_real'] == False])


عرض أول 10 صفوف من البيانات:
   serial_number            qr_code_path  is_real
0     3318969548  qr_code_3318969548.png     True
1     6798490167  qr_code_6798490167.png     True
2     8659305112  qr_code_8659305112.png     True
3     3876647307  qr_code_3876647307.png     True
4     4492775533  qr_code_4492775533.png     True
5     2497155798  qr_code_2497155798.png     True
6     5224108665  qr_code_5224108665.png     True
7     7630572957  qr_code_7630572957.png     True
8     7951805372  qr_code_7951805372.png     True
9     3396715401  qr_code_3396715401.png     True

عدد الأرقام الحقيقية: 1000
عدد الأرقام المزيفة: 1000

عرض البيانات الحقيقية:
     serial_number            qr_code_path  is_real
0       3318969548  qr_code_3318969548.png     True
1       6798490167  qr_code_6798490167.png     True
2       8659305112  qr_code_8659305112.png     True
3       3876647307  qr_code_3876647307.png     True
4       4492775533  qr_code_4492775533.png     True
..             ...             

In [5]:
import pandas as pd
from PIL import Image


# لعرض QR code معين
def display_qr_code(qr_path):
    img = Image.open(qr_path)
    img.show()

# عرض QR code للرقم التسلسلي الأول (على سبيل المثال)
qr_path_first_real = df[df['is_real'] == True].iloc[0]['qr_code_path']
qr_path_first_fake = df[df['is_real'] == False].iloc[0]['qr_code_path']

print("\nعرض QR Code للرقم التسلسلي الحقيقي الأول:")
display_qr_code(qr_path_first_real)

print("\nعرض QR Code للرقم التسلسلي المزيف الأول:")
display_qr_code(qr_path_first_fake)



عرض QR Code للرقم التسلسلي الحقيقي الأول:

عرض QR Code للرقم التسلسلي المزيف الأول:


In [6]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.preprocessing import image


In [7]:
# تحميل البيانات من CSV (يجب أن يكون لديك الأعمدة المناسبة مثل الرقم التسلسلي وQR code path)
df = pd.read_csv('serial_numbers_with_qr_codes_separated.csv')

# هنا تحتاج لتحميل الصور من مسارات QR code وحولها إلى numpy arrays
# سنفترض أنك خزنت مسارات الصور في عمود 'qr_code_path'

def load_images(qr_code_paths):
    images = []
    for path in qr_code_paths:
        img = image.load_img(path, target_size=(64, 64))  # Resize الصورة إلى 64x64
        img_array = image.img_to_array(img) / 255.0  # تحويل الصورة إلى مصفوفة وتطبيعها
        images.append(img_array)
    return np.array(images)

# تحميل صور QR code
qr_images = load_images(df['qr_code_path'])


In [8]:
import numpy as np

# مثال على دالة encoding تقوم بتحويل الرقم التسلسلي إلى تمثيل ثابت
def encode_serial_number(serial):
    # على سبيل المثال، يمكن تحويل الرقم التسلسلي إلى تمثيل عددي
    return np.array([int(digit) for digit in str(serial)])

# البيانات الوهمية
df = pd.DataFrame({
    'serial_number': ['1234567890', '0987654321', '5678901234']  # أرقام تسلسلية كمثال
})

# تطبيق الدالة على الأرقام التسلسلية
serial_numbers = np.array([encode_serial_number(serial) for serial in df['serial_number']])

# تأكد من أن جميع الأرقام التسلسلية تم تمثيلها على شكل مصفوفة أحادية البُعد
print(serial_numbers)


[[1 2 3 4 5 6 7 8 9 0]
 [0 9 8 7 6 5 4 3 2 1]
 [5 6 7 8 9 0 1 2 3 4]]


In [10]:

print(df.columns)

import pandas as pd

# قم بتحميل البيانات من ملف CSV
df = pd.read_csv('serial_numbers_with_qr_codes_separated.csv')

# تحقق من الأعمدة في DataFrame
print(df.columns)

# تحقق من بعض البيانات للتأكد من أن عمود 'is_real' موجود
print(df.head())


Index(['serial_number'], dtype='object')
Index(['serial_number', 'qr_code_path', 'is_real'], dtype='object')
   serial_number            qr_code_path  is_real
0     3318969548  qr_code_3318969548.png     True
1     6798490167  qr_code_6798490167.png     True
2     8659305112  qr_code_8659305112.png     True
3     3876647307  qr_code_3876647307.png     True
4     4492775533  qr_code_4492775533.png     True


In [11]:
# تقسيم البيانات إلى بيانات تدريب وتحقق

X_train, X_val, y_train, y_val = train_test_split(qr_images, df['is_real'], test_size=0.2, random_state=42)


In [12]:
# بناء نموذج CNN بسيط
model = Sequential([
    Conv2D(32, (3, 3), activation='relu', input_shape=(64, 64, 3)),
    MaxPooling2D(2, 2),
    Flatten(),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')  # استخدم sigmoid للتصنيف بين حقيقي ومزيف
])

model.compile(optimizer=Adam(), loss='binary_crossentropy', metrics=['accuracy'])


/usr/local/lib/python3.11/dist-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
# تدريب النموذج
history = model.fit(X_train, y_train, epochs=10, validation_data=(X_val, y_val))


Epoch 1/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 7s 115ms/step - accuracy: 0.4881 - loss: 1.1860 - val_accuracy: 0.4975 - val_loss: 0.6933
Epoch 2/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - accuracy: 0.4906 - loss: 0.6952 - val_accuracy: 0.4975 - val_loss: 0.7018
Epoch 3/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 4s 85ms/step - accuracy: 0.5228 - loss: 0.6910 - val_accuracy: 0.5075 - val_loss: 0.6927
Epoch 4/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 6s 119ms/step - accuracy: 0.4996 - loss: 0.6948 - val_accuracy: 0.5225 - val_loss: 0.6927
Epoch 5/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 9s 86ms/step - accuracy: 0.5611 - loss: 0.6849 - val_accuracy: 0.5025 - val_loss: 0.6968
Epoch 6/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 6s 100ms/step - accuracy: 0.5496 - loss: 0.6856 - val_accuracy: 0.5175 - val_loss: 0.6942
Epoch 7/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 5s 92ms/step - accuracy: 0.5708 - loss: 0.6840 - val_accuracy: 0.5125 - val_loss: 0.6928
Epoch 8/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 6s 118ms/step - accuracy: 0.5779 - loss: 0.6798 - val_accuracy: 0.5225

In [14]:
# تقييم النموذج
val_loss, val_accuracy = model.evaluate(X_val, y_val)
print(f"Validation Accuracy: {val_accuracy * 100:.2f}%")


13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5195 - loss: 0.6981
Validation Accuracy: 52.50%
